RazorPagesHandlers/Pages/Categories/Create.cshtml.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorPagesHandlers.Data;

namespace RazorPagesHandlers.Pages.Categories
{
    public class CreateModel : PageModel
    {

        private readonly SimpleDbContext _dbContext;

        public CreateModel(SimpleDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        [BindProperty]
        public Category Category { get; set; }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _dbContext.Categories.Add(Category);
            await _dbContext.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

RazorPagesHandlers/Pages/Categories/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using RazorPagesHandlers.Data;
using System.Threading.Tasks;

namespace RazorPagesHandlers.Pages.Categories
{
    public class EditModel : PageModel
    {
        private readonly SimpleDbContext _dbContext;

        public EditModel(SimpleDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        [BindProperty]
        public Category Category { get; set; }

        public async Task<IActionResult> OnGetAsync(int id)
        {
            Category = await _dbContext.Categories.FindAsync(id);

            if (Category == null)
            {
                return RedirectToPage("Categories");
            }

            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _dbContext.Attach(Category).State = EntityState.Modified;

            try
            {
                await _dbContext.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException ex)
            {
                
            }

            return RedirectToPage("./Index");
        }
    }
}

RazorPagesHandlers/Pages/Categories/Index.cshtml.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorPagesHandlers.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;

namespace RazorPagesHandlers.Pages.Categories
{
    public class IndexModel : PageModel
    {
        private readonly SimpleDbContext _dbContext;

        public IndexModel(SimpleDbContext dbContext)
        {
            _dbContext = dbContext;
        }    

        public List<Category> Categories { get; private set; }

        public async Task OnGetAsync()
        {
            Categories = await _dbContext.Categories.ToListAsync();
        }

        public async Task<IActionResult> OnPostDeleteAsync(int id)
        {
            var category = await _dbContext.Categories.FindAsync(id);

            if (category != null)
            {
                _dbContext.Categories.Remove(category);
                await _dbContext.SaveChangesAsync();
            }

            return RedirectToPage();
        }
    }
}

RazorPagesHandlers/Pages/Categories/IndexParamsForm.cshtml.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorPagesHandlers.Data;
using Microsoft.EntityFrameworkCore;
using System.Linq;

namespace RazorPagesHandlers.Pages.Categories
{
    public class IndexParamsFormModel : PageModel
    {
        private readonly SimpleDbContext _dbContext;

        public IndexParamsFormModel(SimpleDbContext dbContext)
        {
            _dbContext = dbContext;
        }    

        public List<Category> Categories { get; private set; }

        public async Task OnGetAsync()
        {
            Categories = await _dbContext.Categories.ToListAsync();
        }

        public async Task OnPostSearchAsync(string query)
        {
            Categories = await _dbContext
                .Categories
                .AsNoTracking()
                .Where(c => !string.IsNullOrEmpty(c.Description) && c.Description.Contains(query))
                .ToListAsync();
        }
    }
}

RazorPagesHandlers/Pages/Categories/IndexParamsRoute.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorPagesHandlers.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;

namespace RazorPagesHandlers.Pages.Categories
{
    public class IndexParamsRouteModel : PageModel
    {
        private readonly SimpleDbContext _dbContext;

        public IndexParamsRouteModel(SimpleDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        public List<Category> Categories { get; private set; }

        public async Task OnGetAsync()
        {
            Categories = await _dbContext.Categories.ToListAsync();
        }

        public async Task OnPostSearchAsync(string query)
        {
            Categories = await _dbContext
                .Categories
                .AsNoTracking()
                .Where(c => !string.IsNullOrEmpty(c.Description) && c.Description.Contains(query))
                .ToListAsync();
        }

        public async Task<IActionResult> OnPostDeleteAsync(int id)
        {
            var category = await _dbContext.Categories.FindAsync(id);

            if (category != null)
            {
                _dbContext.Categories.Remove(category);
                await _dbContext.SaveChangesAsync();
            }

            return RedirectToPage();
        }
    }
}

RazorPagesHandlers/Pages/Categories/Multi.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorPagesHandlers.Data;
using System.Threading.Tasks;

namespace RazorPagesHandlers.Pages.Categories
{
    public class MultiModel : PageModel
    {
        private readonly SimpleDbContext _dbContext;

        public MultiModel(SimpleDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        [BindProperty]
        public Category Category { get; set; }

        public async Task<IActionResult> OnGetAsync(int id)
        {
            Category = await _dbContext.Categories.FindAsync(id);

            if (Category == null)
            {
                return RedirectToPage("Categories");
            }

            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _dbContext.Categories.Add(Category);
            await _dbContext.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

RazorPagesHandlers/Pages/Categories/MultiPost.cshtml.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorPagesHandlers.Data;

namespace RazorPagesHandlers.Pages
{
    public class MultiPostModel : PageModel
    {

        private readonly SimpleDbContext _dbContext;

        public MultiPostModel(SimpleDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        [BindProperty]
        public Category Category { get; set; }

        public async Task<IActionResult> OnPostFirstAsync()
        {
            return await InsertCategory("First");
        }
      
        public async Task<IActionResult> OnPostSecondAsync()
        {
            return await InsertCategory("Second");
        }

        private async Task<IActionResult> InsertCategory(string name)
        {
            Category.Name = name;
            _dbContext.Categories.Add(Category);
            await _dbContext.SaveChangesAsync();

            return RedirectToPage("./Categories/Index");
        }
    }
}

RazorPagesHandlers/Pages/Categories/SinglePost.cshtml.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorPagesHandlers.Data;

namespace RazorPagesHandlers.Pages
{
    public class SinglePostModel : PageModel
    {
        private readonly SimpleDbContext _dbContext;

        public SinglePostModel(SimpleDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        [BindProperty]
        public Category Category { get; set; }

        public async Task<IActionResult> OnPostFirstAsync()
        {
            Category.Name = "First";
            _dbContext.Categories.Add(Category);
            await _dbContext.SaveChangesAsync();

            return RedirectToPage("./Categories/Index");
        }
    }
}

RazorPagesHandlers/Pages/Categories/Create.cshtml
@page
@model CreateModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers


<div>
    <p>
        Create new Category.
    </p>
    <div asp-validation-summary="All"></div>
    <form method="POST">
        <div>Name: <input asp-for="Category.Name" /></div>
        <div>Description: <input asp-for="Category.Description" /></div>
        <button type="submit" class="btn btn-primary">Save</button>
    </form>

</div>

RazorPagesHandlers/Pages/Categories/Edit.cshtml
@page "{id:int}"
@model EditModel
@{
}
@{
    ViewData["Title"] = "Edit Category";
}

<h1>Edit Category - @Model.Category.Id</h1>

<form method="post">
    <div asp-validation-summary="All"></div>
    <input asp-for="Category.Id" type="hidden" />
    <div>
        <label asp-for="Category.Name"></label>
        <div>
            <input asp-for="Category.Name" />
            <span asp-validation-for="Category.Name"></span>
        </div>
        <label asp-for="Category.Description"></label>
        <div>
            <input asp-for="Category.Description" />
            <span asp-validation-for="Category.Description"></span>
        </div>
    </div>

    <div>
        <button type="submit" class="btn btn-primary">Save</button>
    </div>

</form>

RazorPagesHandlers/Pages/Categories/Index.cshtml
@page
@model IndexModel

<h1>Categories</h1>

<a asp-page="./Create">Create New</a>

<form method="post">
    <table class="table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Description</th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var category in Model.Categories)
            {
                <tr>
                    <td>@category.Id</td>
                    <td>@category.Name</td>
                    <td>@category.Description</td>
                    <td>
                        <a class="btn btn-primary" asp-page="./Edit" asp-route-id="@category.Id">Edit</a>
                    </td>
                    <td>
                        <button class="btn btn-warning"
                                type="submit"
                                asp-page-handler="delete"
                                asp-route-id="@category.Id">
                            Delete
                        </button>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</form>

RazorPagesHandlers/Pages/Categories/IndexParamsForm.cshtml
@page
@model IndexParamsFormModel

<h1>Categories</h1>


<div>
    <form method="post">
        <input type="text" name="query" />
        <button asp-page-handler="search">Search</button>
    </form>
</div>

<form method="post">
    <table class="table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Description</th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var category in Model.Categories)
            {
                <tr>
                    <td>@category.Id</td>
                    <td>@category.Name</td>
                    <td>@category.Description</td>
                    <td>
                        <a class="btn btn-primary" asp-page="./Edit" asp-route-id="@category.Id">Edit</a>
                    </td>
                    <td>
                        <button class="btn btn-warning"
                                type="submit"
                                asp-page-handler="delete"
                                asp-route-id="@category.Id">
                            Delete
                        </button>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</form>

RazorPagesHandlers/Pages/Categories/IndexParamsRoute.cshtml
@page
@model IndexParamsRouteModel

<h1>Categories</h1>


<div>
    <form method="post" asp-page-handler="search" asp-route-query="Core">    
        <button>Search "Core"</button>
    </form>
</div>

<div>
    <form method="post" asp-page-handler="delete" asp-route-id="1">
        <button>Delete ID 1</button>
    </form>
</div>

<form method="post">
    <table class="table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Description</th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var category in Model.Categories)
            {
                <tr>
                    <td>@category.Id</td>
                    <td>@category.Name</td>
                    <td>@category.Description</td>
                    <td>
                        <a class="btn btn-primary" asp-page="./Edit" asp-route-id="@category.Id">Edit</a>
                    </td>
                    <td>
                        <button class="btn btn-warning"
                                type="submit"
                                asp-page-handler="delete"
                                asp-route-id="@category.Id">
                            Delete
                        </button>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</form>

RazorPagesHandlers/Pages/Categories/Multi.cshtml
@page "{id:int}"
@model MultiModel

@{
    ViewData["Title"] = "Multi";
}
POST and GET handler

<form method="post">
    <div>Name: <input asp-for="Category.Name" /></div>
    <div>Description: <input asp-for="Category.Description" /></div>
    <button type="submit" class="btn btn-primary">Create New</button>
</form>

RazorPagesHandlers/Pages/Categories/MultiPost.cshtml
@page
@model MultiPostModel

<div>
    <p>
        Create new Category.
    </p>
    <div asp-validation-summary="All"></div>
    <form method="POST">
        <div> Description: <input asp-for="Category.Description" />
            <input type="submit" value="Save First" asp-page-handler="First" class="btn btn-primary btn-xs">
        </div>
    </form>


    <form method="POST">
        <div>  Description: <input asp-for="Category.Description" />
            <input type="submit" value="Save Second" asp-page-handler="Second" class="btn btn-primary btn-xs">
        </div>
    </form>
</div>

RazorPagesHandlers/Pages/Categories/SinglePost.cshtml
@page
@model SinglePostModel

<div>
    <p>
        Create new Category.
    </p>
    <div asp-validation-summary="All"></div>

    <form method="POST">
        <div>
            Description: <input asp-for="Category.Description" />
            <input type="submit" value="Save First" asp-page-handler="First" class="btn btn-primary btn-xs">
        </div>
    </form>

</div>